#!/usr/bin/env node
/**
 * Builds sitemap.xml from the pages that actually exist plus the project
 * detail pages declared in js/site/data/projects.js.
 *
 *   node tools/build-sitemap.mjs
 *
 * The canonical base comes from SITE.url in js/site/config.js, so changing
 * the domain is a one-line edit and nothing here can drift out of sync.
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { SITE } from '../js/site/config.js';
import { PROJECTS } from '../js/site/data/projects.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const base = SITE.url.replace(/\/+$/, '');

const WEIGHTS = {
  'index.html': ['1.0', 'weekly'],
  'portfolio.html': ['0.9', 'weekly'],
  'game.html': ['0.9', 'weekly'],
  'services.html': ['0.8', 'monthly'],
  'about.html': ['0.8', 'monthly'],
  'contact.html': ['0.8', 'monthly'],
  'privacy.html': ['0.5', 'yearly'],
  '404.html': ['0.3', 'yearly'],
};

const urls = [];

for (const file of readdirSync(ROOT).filter((f) => f.endsWith('.html'))) {
  const [priority, changefreq] = WEIGHTS[file] || ['0.6', 'monthly'];
  urls.push({
    loc: file === 'index.html' ? `${base}/` : `${base}/${file}`,
    priority,
    changefreq,
  });
}

// Project detail pages are rendered by project.html from the query string.
for (const project of PROJECTS) {
  urls.push({
    loc: `${base}/project.html?slug=${encodeURIComponent(project.slug)}`,
    priority: '0.7',
    changefreq: 'monthly',
  });
}

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by tools/build-sitemap.mjs — do not edit by hand. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...urls.map((u) => [
    '  <url>',
    `    <loc>${u.loc.replace(/&/g, '&amp;')}</loc>`,
    `    <changefreq>${u.changefreq}</changefreq>`,
    `    <priority>${u.priority}</priority>`,
    '  </url>',
  ].join('\n')),
  '</urlset>',
  '',
].join('\n');

writeFileSync(join(ROOT, 'sitemap.xml'), xml, 'utf8');
console.log(`wrote sitemap.xml with ${urls.length} URLs (${PROJECTS.length} project pages)`);
